Mala izmena u USAGE_TIME
Imam problem ovde. Lepo radi sa stats.norm ali kad mu dam druge raspodele ono ne radi. Na primer za stats.lognorm da TypeError: _parse_args_rvs() missing 1 required positional argument: 's' gresku iako dam s